# Site settings
title: Ilir Kosumi 
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ilir Kosumi
user_description: I'm a QA Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been involved in testing cloud-based solutions around big data and process mining. 
user_title: QA Engineer
email: ilirkosumi@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
